Vagrant.require_version ">= 1.5.0"

Vagrant.configure(2) do |config|
  config.vm.define "aurora_jessie"
  config.vm.box = "debian/jessie64"

  config.vm.hostname = "localhost"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "4096"]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end
  config.vm.provision "shell", path: "provision.sh"
end
